In [1]:
import torch

## Example 1

In [2]:
x= torch.tensor(3.0, requires_grad= True)
## if requires grad is true then pytorch tracks each and every operation done with x
x

tensor(3., requires_grad=True)

In [5]:
y= x**2 + 2*x
y

tensor(15., grad_fn=<AddBackward0>)

In [6]:
# calculate dy/dx
y.backward()
x.grad

tensor(8.)

## Example 2

In [9]:
a= torch.tensor(10.0, requires_grad= True)
a


tensor(10., requires_grad=True)

In [10]:
b= a**2 + 5
b

tensor(105., grad_fn=<AddBackward0>)

In [11]:
c= torch.cos(b)
c

tensor(-0.2410, grad_fn=<CosBackward0>)

In [12]:
# derivative of dc/da
c.backward()
a.grad

tensor(19.4107)

## Example 3
    - Finding the gradient of w and b of a perceptron
    - x is input and y is the actual output
    - We are using Sigmoid as activation function

In [14]:
x= torch.tensor(6.9)
y= torch.tensor(0.0)


# we arent doing required grad = True becasue we donot want to calculate derivative with respect to x

In [17]:
w= torch.tensor(1.0, requires_grad= True)
b= torch.tensor(0.0, requires_grad= True)

print(w)
print(b)

tensor(1., requires_grad=True)
tensor(0., requires_grad=True)


In [18]:
# forward propagation
z= w*x + b
z

tensor(6.9000, grad_fn=<AddBackward0>)

In [19]:
y_pred= torch.sigmoid(z)
y_pred

tensor(0.9990, grad_fn=<SigmoidBackward0>)

In [20]:
def binary_cross_entropy(y_pred, y_true):
    return (-y_true*torch.log(y_pred)- (1-y_true)*torch.log(1-y_pred))

In [21]:
loss= binary_cross_entropy(y_pred, y)
loss

tensor(6.9010, grad_fn=<SubBackward0>)

In [22]:
## compute dy/dw
loss.backward()
w.grad

tensor(6.8931)

In [23]:
b.grad

tensor(0.9990)

## Autograd with vectors

In [25]:
m= torch.tensor(data= [1.0, 2.0, 3.0], requires_grad= True)
m

tensor([1., 2., 3.], requires_grad=True)

In [27]:
n= m*2
n

tensor([2., 4., 6.], grad_fn=<MulBackward0>)

In [30]:
# n.backward()
# if I do m.grad
## It eill throw below error
### RuntimeError: grad can be implicitly created only for scalar outputs

In [34]:
o= m.mean() + 2
o

tensor(4., grad_fn=<AddBackward0>)

In [36]:
o.backward()
m.grad

# 3 output with respect to each of 3 x

tensor([0.6667, 0.6667, 0.6667])

## Clearing grad
    - After each forward prop and backward we need to clear the grad because previous grad will be added 

In [43]:
x= torch.tensor(data= 5.0, requires_grad=True)
x

tensor(5., requires_grad=True)

In [44]:
# without clearing grad
for i in range (5):
    y= x**2 + 2*x
    y.backward()
    x.grad
    print("y: ", y)
    print("x.grad: ", x.grad)

y:  tensor(35., grad_fn=<AddBackward0>)
x.grad:  tensor(12.)
y:  tensor(35., grad_fn=<AddBackward0>)
x.grad:  tensor(24.)
y:  tensor(35., grad_fn=<AddBackward0>)
x.grad:  tensor(36.)
y:  tensor(35., grad_fn=<AddBackward0>)
x.grad:  tensor(48.)
y:  tensor(35., grad_fn=<AddBackward0>)
x.grad:  tensor(60.)


In [46]:
x.grad.zero_()  # cleared previous grad
# with clearing grad
for i in range (5):
    y= x**2 + 2*x
    y.backward()
    x.grad
    print("y: ", y)
    print("x.grad: ", x.grad)
    x.grad.zero_()

y:  tensor(35., grad_fn=<AddBackward0>)
x.grad:  tensor(12.)
y:  tensor(35., grad_fn=<AddBackward0>)
x.grad:  tensor(12.)
y:  tensor(35., grad_fn=<AddBackward0>)
x.grad:  tensor(12.)
y:  tensor(35., grad_fn=<AddBackward0>)
x.grad:  tensor(12.)
y:  tensor(35., grad_fn=<AddBackward0>)
x.grad:  tensor(12.)


## Disable gradient tracking
    - After training NN we can just disable unnecessary gradient tracking so it wont take spacem

In [47]:
x= torch.tensor(data= 5.0, requires_grad= True)
x

tensor(5., requires_grad=True)

In [50]:
x.requires_grad= False

In [51]:
x

tensor(5.)

In [53]:
x= torch.tensor(data= 5.0, requires_grad= True)
x

tensor(5., requires_grad=True)

In [54]:
# using .requires_grad_(False)
x.requires_grad_(False)
x

tensor(5.)

In [55]:
x= torch.tensor(data= 5.0, requires_grad= True)
x

tensor(5., requires_grad=True)

In [58]:
# using detach; this helps to create new tensor with same value of the previous tensor with requires_grad= False
z= x.detach()
print(x)
print(z)

print("-"* 50)

y= x*2
y1= z*2

print(y, y1)

tensor(5., requires_grad=True)
tensor(5.)
--------------------------------------------------
tensor(10., grad_fn=<MulBackward0>) tensor(10.)


In [59]:
x

tensor(5., requires_grad=True)

In [60]:
# using torch.no_grad

with torch.no_grad():
    y= x* 2

print(y)

z= x*2
print(z)
 

tensor(10.)
tensor(10., grad_fn=<MulBackward0>)
