In [1]:
from sklearn.datasets import make_classification

In [4]:
x, y= make_classification(
    n_samples= 10,
    n_redundant= 0,
    n_features= 3,
    random_state= 42,

)

In [5]:
x

array([[-0.58723065, -1.97171753, -1.05771093],
       [ 1.06833894, -0.97007347,  0.2088636 ],
       [-1.14021544, -0.83879234,  0.82254491],
       [-0.9382051 , -0.54304815, -1.22084365],
       [ 1.72725924, -1.18582677, -1.95967012],
       [-2.8953973 ,  1.97686236,  0.19686124],
       [-1.96287438, -0.99225135, -1.32818605],
       [ 1.89969252,  0.83444483,  0.17136828],
       [-0.72063436, -0.96059253, -0.01349722],
       [ 1.77736657,  1.51157598,  0.73846658]])

In [6]:
y

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [7]:
# converting array into tensors

import torch
x= torch.from_numpy(x).float()
y= torch.tensor(data= y, dtype= torch.float32)

In [8]:
x

tensor([[-0.5872, -1.9717, -1.0577],
        [ 1.0683, -0.9701,  0.2089],
        [-1.1402, -0.8388,  0.8225],
        [-0.9382, -0.5430, -1.2208],
        [ 1.7273, -1.1858, -1.9597],
        [-2.8954,  1.9769,  0.1969],
        [-1.9629, -0.9923, -1.3282],
        [ 1.8997,  0.8344,  0.1714],
        [-0.7206, -0.9606, -0.0135],
        [ 1.7774,  1.5116,  0.7385]])

In [9]:
y

tensor([0., 1., 0., 1., 1., 0., 0., 1., 0., 1.])

In [10]:
from torch.utils.data import Dataset, DataLoader


In [16]:
# dataset class is used for fetching data from the memory

class CustomData(Dataset):

    def __init__(self, features, label):     #features is inputs and label is output; loading the data
        self.features= features
        self.label= label


    def __len__(self):
        return self.features.shape[0]     #returns the total number of rows in our data



    def __getitem__(self, index):
        return self.features[index], self.label[index]   # returns respective row of our data

In [17]:
data= CustomData(x, y)

In [18]:
data[5]

(tensor([-2.8954,  1.9769,  0.1969]), tensor(0.))

In [19]:
len(data)

10

In [20]:
## getting batches of data
dataloader= DataLoader(dataset= data, batch_size= 2, shuffle= True)

for feature, label in dataloader:
    print(feature)
    print(label)
    print("-"*50)

tensor([[-2.8954,  1.9769,  0.1969],
        [ 1.7774,  1.5116,  0.7385]])
tensor([0., 1.])
--------------------------------------------------
tensor([[-0.7206, -0.9606, -0.0135],
        [ 1.7273, -1.1858, -1.9597]])
tensor([0., 1.])
--------------------------------------------------
tensor([[-1.9629, -0.9923, -1.3282],
        [-1.1402, -0.8388,  0.8225]])
tensor([0., 0.])
--------------------------------------------------
tensor([[ 1.0683, -0.9701,  0.2089],
        [ 1.8997,  0.8344,  0.1714]])
tensor([1., 1.])
--------------------------------------------------
tensor([[-0.5872, -1.9717, -1.0577],
        [-0.9382, -0.5430, -1.2208]])
tensor([0., 1.])
--------------------------------------------------


In [21]:
dataloader= DataLoader(dataset= data, batch_size= 1, shuffle= False)

for feature, label in dataloader:
    print(feature)
    print(label)
    print("-"*50)

tensor([[-0.5872, -1.9717, -1.0577]])
tensor([0.])
--------------------------------------------------
tensor([[ 1.0683, -0.9701,  0.2089]])
tensor([1.])
--------------------------------------------------
tensor([[-1.1402, -0.8388,  0.8225]])
tensor([0.])
--------------------------------------------------
tensor([[-0.9382, -0.5430, -1.2208]])
tensor([1.])
--------------------------------------------------
tensor([[ 1.7273, -1.1858, -1.9597]])
tensor([1.])
--------------------------------------------------
tensor([[-2.8954,  1.9769,  0.1969]])
tensor([0.])
--------------------------------------------------
tensor([[-1.9629, -0.9923, -1.3282]])
tensor([0.])
--------------------------------------------------
tensor([[1.8997, 0.8344, 0.1714]])
tensor([1.])
--------------------------------------------------
tensor([[-0.7206, -0.9606, -0.0135]])
tensor([0.])
--------------------------------------------------
tensor([[1.7774, 1.5116, 0.7385]])
tensor([1.])
-------------------------------------