In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU {torch.cuda.get_device_name(0)}")

else:
    print("GPU not available. Using CPU")

GPU is available
Using GPU Tesla T4


## Creating Tensor

In [3]:
# using empty
a= torch.empty(2, 3)
print(type(a))
a

<class 'torch.Tensor'>


tensor([[1.8916e+23, 7.1846e+22, 1.2845e+31],
        [7.1554e+22, 1.8492e+31, 7.8675e+34]])

In [4]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# using rand
## generates tensor for specified shape having values between 0 and 1
torch.rand(2,3)

tensor([[0.7370, 0.0926, 0.1685],
        [0.7995, 0.1617, 0.1843]])

In [7]:
## we can also generate same random values using seed
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [8]:
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [9]:
# using tensor
## used to create tensors like we want

torch.tensor([[1, 2, 3],
              [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
# Other methods
## using arange
### below code generates 1d tensor from 0 t0 10 with step 2
print("Using Eye -> ", torch.arange(0, 10, 2))


## using linspace
### generates linearly 5 numbers from 0 to 10
print("Using linspace -> ", torch.linspace(0, 10, 5))


##using eye
### generates identity matrix of m*m
print("Using eye -> \n", torch.eye(3))


##using full
### generates tensors of specific shape with all items same as specified
print("Using full -> \n", torch.full((2, 3), 5))

Using Eye ->  tensor([0, 2, 4, 6, 8])
Using linspace ->  tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
Using eye -> 
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Using full -> 
 tensor([[5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [11]:
x= torch.tensor([[1, 2, 3],
                 [4, 5, 6]])

x.shape

torch.Size([2, 3])

In [12]:
# find the dimension of tensors
x.ndim

2

In [13]:
# we can also make tensors with the same shape of x
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [14]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [15]:
torch.full_like(x, 10)

#and so on

tensor([[10, 10, 10],
        [10, 10, 10]])

## Datatype used in value of tensor

In [16]:
x.dtype

torch.int64

In [17]:
# create a tensor with the specific datatype
torch.ones((2, 3), dtype= torch.int64)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x, dtype= torch.float64)   
## we must give dtype while usinf rand_like because it generates float value between 0 and 1

tensor([[0.0526, 0.5262, 0.4768],
        [0.9552, 0.9288, 0.0835]], dtype=torch.float64)

In [ ]:
torch.tensor(([[1, 2, 3],
               [4, 5, 6]]), dtype= torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [20]:
#change the datatype of an tensor
tensor= torch.zeros_like(x, dtype= torch.int32)
tensor= tensor.to(dtype= torch.float64)
tensor.dtype

torch.float64

## Mathematical Opearions

### 1. Scalar Operations

In [21]:
x= torch.rand(2, 2)
x

tensor([[0.2666, 0.6274],
        [0.2696, 0.4414]])

In [22]:
# addition
x+ 2

tensor([[2.2666, 2.6274],
        [2.2696, 2.4414]])

In [23]:
# subtraction
x- 2

tensor([[-1.7334, -1.3726],
        [-1.7304, -1.5586]])

In [24]:
# multiplication
x*2

tensor([[0.5332, 1.2549],
        [0.5393, 0.8827]])

In [25]:
# division
x/3

tensor([[0.0889, 0.2091],
        [0.0899, 0.1471]])

In [26]:
# integer division; only integer part of quotient is shown
((x+1)*100)//3

tensor([[42., 54.],
        [42., 48.]])

In [27]:
# modulus
((x+1)*100)%2

tensor([[0.6580, 0.7449],
        [0.9632, 0.1364]])

In [28]:
# power
x**2

tensor([[0.0711, 0.3937],
        [0.0727, 0.1948]])

In [29]:
## we can also perform element wise operation between 2 tensors same as above

### 2. Reduction Operation

In [30]:
e= torch.randint(size= (2, 3), low= 0, high= 10, dtype= torch.float64)
e

tensor([[3., 1., 9.],
        [3., 1., 9.]], dtype=torch.float64)

In [31]:
# to find the sum of all the elements inside tensor
torch.sum(e)

tensor(26., dtype=torch.float64)

In [32]:
# sum along column
torch.sum(e, dim= 0, dtype= torch.int32) # dim = 1 for rows

tensor([ 6,  2, 18], dtype=torch.int32)

In [33]:
# mean
torch.mean(e)  #tensor should be a float for mean

tensor(4.3333, dtype=torch.float64)

In [34]:
#mean along row
torch.mean(e, dim= 1)

tensor([4.3333, 4.3333], dtype=torch.float64)

In [35]:
# for median
## we can also perform row wise or column wise as above
torch.median(e)

# similiarly .min, .max, .var, .cov, .std

tensor(3., dtype=torch.float64)

In [36]:
# argmax
## gives the position of largest item. Similiarly argmin for postion of smallest item
torch.argmax(e)

tensor(2)

In [ ]:
torch.cov(e)

tensor([[17.3333, 17.3333],
        [17.3333, 17.3333]], dtype=torch.float64)

## Matrix Operations

In [38]:
a= torch.randint(size= (2, 3), low= 0, high = 5, dtype= torch.float32)
b= torch.rand((3, 2))

In [39]:
# matrix multiplication
torch.matmul(a, b)

tensor([[4.0963, 5.9185],
        [2.2186, 1.3693]])

In [40]:
x= torch.tensor([1, 2, 3])
y= torch.tensor([4, 5, 6])

In [41]:
#dot product
torch.dot(x, y)

tensor(32)

In [42]:
a

tensor([[2., 4., 2.],
        [0., 0., 4.]])

In [43]:
#transpose
torch.transpose(a, 0, 1)

tensor([[2., 0.],
        [4., 0.],
        [2., 4.]])

In [44]:
# deteminant
torch.manual_seed(42)
torch.det(torch.rand(size= (3, 3)))

tensor(-0.5282)

In [45]:
# inverse
torch.manual_seed(42)
torch.inverse(torch.rand(size= (3, 3)))

tensor([[ 0.2074,  1.0543, -0.7579],
        [ 1.4166, -1.3853,  0.3083],
        [-1.2516,  0.8811,  1.0095]])

In [46]:
# simliarly we can use comparision operation like greater than, less than between tesnor and scalar and tensor and other tensor too(element wise)

In [47]:
x


tensor([1, 2, 3])

In [48]:
# Special Function
print("log -> ", torch.log(x))
print("exp -> ", torch.exp(x))
print("sqrt -> ", torch.sqrt(x))
print("sigmoid -> ", torch.sigmoid(x))
print("tanh -> ", torch.tanh(x))
print("relu -> ", torch.relu(x))

# they all perform element wise of tensor

log ->  tensor([0.0000, 0.6931, 1.0986])
exp ->  tensor([ 2.7183,  7.3891, 20.0855])
sqrt ->  tensor([1.0000, 1.4142, 1.7321])
sigmoid ->  tensor([0.7311, 0.8808, 0.9526])
tanh ->  tensor([0.7616, 0.9640, 0.9951])
relu ->  tensor([1, 2, 3])


In [49]:
a

tensor([[2., 4., 2.],
        [0., 0., 4.]])

In [50]:
# for sigmoid; sigmoid expects the input to be in float
torch.softmax(a, dim= 0)

tensor([[0.8808, 0.9820, 0.1192],
        [0.1192, 0.0180, 0.8808]])

## Inplace Operations

In [51]:
m= torch.rand(size= (2,3))
n= torch.rand(size=(2, 3))

print(m)
print(n)

tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411]])
tensor([[0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696]])


In [52]:
# the following code adds m and n and store it in m
m.add_(n)
m

tensor([[0.5626, 1.8200, 1.1675],
        [1.1360, 1.1952, 1.0107]])

In [53]:
n.relu_()

tensor([[0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696]])

In [54]:
n

tensor([[0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696]])

## Copying a Tensor

In [ ]:
z= torch.rand((2, 3))
z


tensor([[0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])

In [56]:
v= z.clone()
v

tensor([[0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])

## Tensor Operations in GPU

In [57]:
torch.cuda.is_available()

True

In [58]:
device= torch.device('cuda')

In [59]:
## Creating a tensor in gpu
gpu_tensor= torch.rand((3, 5), device= device)
gpu_tensor

tensor([[0.6130, 0.0101, 0.3984, 0.0403, 0.1563],
        [0.4825, 0.7362, 0.4060, 0.5189, 0.2867],
        [0.2416, 0.9228, 0.8299, 0.0342, 0.3879]], device='cuda:0')

In [ ]:
a

tensor([[2., 4., 2.],
        [0., 0., 4.]])

In [ ]:
# transfering the cpu tensors into gpu
a_gpu= a.to(device = device)

In [62]:
a_gpu

tensor([[2., 4., 2.],
        [0., 0., 4.]], device='cuda:0')

## Reshaping Tensors

In [67]:
tensor= torch.ones(size= (3,2,1,4))
tensor.shape

torch.Size([3, 2, 1, 4])

In [64]:
tensor

tensor([[[[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]]]])

In [ ]:
# rehshape
tensor.reshape(6, 4)    #during rehsape the product of shapes must be same

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [66]:
#flatten(converts to 1d)
tensor.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.])

In [70]:
# permute
permuted_tensor= tensor.permute(3, 2, 1, 0)
permuted_tensor.shape

torch.Size([4, 1, 2, 3])

In [ ]:
# unsqueeze
## adds dimension of 1 in desired postion
unsq_tensor= tensor.unsqueeze(1)
unsq_tensor

tensor([[[[[1., 1., 1., 1.]],

          [[1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.]],

          [[1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.]],

          [[1., 1., 1., 1.]]]]])

In [73]:
unsq_tensor.shape

torch.Size([3, 1, 2, 1, 4])

In [74]:
# squeeze is opposite of squeeze
tensor.squeeze().shape

torch.Size([3, 2, 4])

## NumPy and PyTorch

In [75]:
import numpy as np

In [76]:
a= torch.tensor(data= [[1,2, 3],
                       [4, 5, 6]])

In [77]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# converting pytorch tensor into numpy array
a_numpy= a.numpy()
a_numpy

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
type(a_numpy)

numpy.ndarray

In [84]:
# converting numpy array to pytorch tensor
b= np.ones(5, dtype= np.int64)
b

array([1, 1, 1, 1, 1])

In [85]:
b_torch= torch.from_numpy(b)
b_torch

tensor([1, 1, 1, 1, 1])

In [86]:
type(b_torch)

torch.Tensor